---
label: Services
hide_body: true
is_partial: false
fields:
- type: file
  name: header_bild
  label: Header Bild
- type: textarea
  name: einleitung
  label: Einleitung
- type: field_group
  name: icon_text_links
  label: Icon Text links
  fields:
  - type: file
    name: icon
    label: Icon
    description: optional
  - type: textarea
    name: content
    label: Content
    config:
      wysiwyg: true
      schema:
        format: html-blocks
- type: textarea
  name: content_rechts
  label: Content rechts
  config:
    wysiwyg: true
    schema:
      format: html-blocks
- type: field_group
  name: zielgruppen
  label: Zielgruppen
  fields:
  - type: field_group_list
    name: zielgruppe
    label: Zielgruppe
    fields:
    - type: text
    - type: textarea
      name: titel
      label: Titel
      config:
        wysiwyg: true
        schema:
          format: html-blocks
    - type: file
      name: bild
      label: Bild
